module.exports = {
  darkMode: "class",
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        'primary-700': ['NeueMontreal-Bold'],
        'primary-500': ['NeueMontreal-Medium'],
        'primary-400': ['NeueMontreal-Regular']
      },
      spacing: {
        space1: '40px',
        space2: '32px',
        space22: '24px',
        space21: '20px',
        space3: '16px',
        space31: '12px',
        space32: '10px',
        space4: '8px',
        space41: '6px',
        space5: '4px',
        space51: '2px',
      },
      borderRadius: {
        radius1: '40px',
        radius2: '16px',
        radius3: '8px',
        radius4: '4px',
        radius5: '2px',
      },
      boxShadow: {
        elevation1: '0px 4px 6px 0px rgba(0, 0, 0, 0.09)',
        elevation2: '0px 3px 1px -2px rgba(0, 0, 0, 0.20)',
      },
      colors: {
        gray: {
          100: "#fdfdfd",
          200: "#fcfcfc",
          300: "#f6f6f6",
          400: "#ececec",
          500: "#eaeaea",
          600: "#e1e1e1",
          700: "#d3d3d3",
          800: "#cacaca",
          900: "#cccccc",
        },
        darkGray: {
          100: "#ededed",
          200: "#787878",
          300: "#777777",
          400: "#757575",
          500: "#737373",
          600: "#727272",
          700: "#717171",
          800: "#7f7f7f",
          900: "#6d6d6d",
        },
        border: "#A3A3A3",
        disabled: "#A3A3A3",
        tertiary: "#737373",
        backgroundSubtle: "#FAFAFA",
        white: "#FFFFFF",
        secondary: "#404040",
        black: "#0A0A0A",
        border2: "#E5E5E5",
        "teal-200": "#B8E4E5",
        neutral: "#525252",
        "subtle": "#FAFAFA",
        "neutral-950": "#0A0A0A",
        "neutral-300": "#D4D4D4",
        "neutral-500": "#A3A3A3",
        "neutral-100": "#F5F5F5",
        subtitle: "#D4D4D4",
        errormessage: "#D9323D",
        "orange-primary": "#FF885D",
        pin: "#f9f9f9",
        primary: "#0A0A0A",
        background: "#FAFAFA",
        transparent: "transparent",
        whiteSubtle: "#FAFAFA",
        // input: "hsl(var(--input))",
        // ring: "hsl(var(--ring))",
        // background: "hsl(var(--background))",
        // foreground: "hsl(var(--foreground))",
        // primary: {
        //   DEFAULT: "hsl(var(--primary))",
        //   foreground: "hsl(var(--primary-foreground))",
        // },
        // destructive: {
        //   DEFAULT: "hsl(var(--destructive))",
        //   foreground: "hsl(var(--destructive-foreground))",
        // },
        // muted: {
        //   DEFAULT: "hsl(var(--muted))",
        //   foreground: "hsl(var(--muted-foreground))",
        // },
        // accent: {
        //   DEFAULT: "hsl(var(--accent))",
        //   foreground: "hsl(var(--accent-foreground))",
        // },
        // popover: {
        //   DEFAULT: "hsl(var(--popover))",
        //   foreground: "hsl(var(--popover-foreground))",
        // },
        // card: {
        //   DEFAULT: "hsl(var(--card))",
        //   foreground: "hsl(var(--card-foreground))",
        // },
      },
    },
  },
  plugins: [],
};
